# Use an official Node.js runtime as a parent image
FROM node:18.12.1

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install Angular CLI and other dependencies
RUN npm install -g @angular/cli@15.2.4
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Build the application
RUN ng build --prod

# Set the command to run when the container starts
CMD ["npm", "start"]
